### ISSUE TITLE
Bug with LDCA ansatz

### ISSUE THREAD

**Issue by thiblouvet** [myQLM/myqlm-fermion#1]
[error_ldca_traceback.txt](https://github.com/myQLM/myqlm-fermion/files/9574829/error_ldca_traceback.txt)

The traceback is attached. The bug occurs on two different computers i've tried. Both with anaconda, one has ubuntu 20.04 and myqlm 1.4.0 and the other has ubuntu 22.04 (latest) and myqlm 1.5.1

The code is the following:

`import numpy as np
from qat.fermion import hamiltonians, circuits#, ElectronicStructureHamiltonian
#from qat.lang.AQASM import H, RX, RY, CNOT, Program
from qat.qpus import get_default_qpu
from qat.plugins import ScipyMinimizePlugin
from qat.core.console import display

def vqe_hubbard(nsites=1, u=2., nsteps=1):
    
    nqbits = 2*nsites
    t = 1.
    

    t_mat = np.zeros((nsites,nsites))
    for i in range(nsites):
        if i > 0:
            t_mat[i,i-1] = - t
        else:
            t_mat[i,nsites-1] = - t
        if i < nsites - 1:
            t_mat[i,i+1] = - t
        else:
            t_mat[i,0] = - t    
    
    hamiltonian = hamiltonians.make_hubbard_model(t_mat = t_mat, U = u, mu = 0.)
    hamiltonian_sp = hamiltonian.to_spin()
    
    circ = circuits.make_ldca_circ(nb_fermionic_modes = nqbits, ncycles = nsteps)
    # circ = circuits.make_general_hwe_circ(nqbits = nqbits, n_cycles = nsteps)
    theta_init = np.random.rand(len(circ.get_variables()))
      
    job = circ.to_job(job_type = "OBS", observable=hamiltonian_sp, nbshots=0)

    
    
    
    optimizer_scipy = ScipyMinimizePlugin(method="COBYLA", tol=1e-3, options={"maxiter": 1000}, x0=theta_init)
    qpu = optimizer_scipy | get_default_qpu()
    result = qpu.submit(job)
    

    
    print(result.value)
    return result.value
    
    
vqe_hubbard()`

**Comment by moliva7** [comment]
Hello Thiblouvet,

Thank you for your input ! Indeed there is a bug with the LDCA circuit in the alpha version of MyQLM-fermion. This bug is fixed in the final release, which will be part of the next MyQLM suite update. This update will be available very soon.

In the meantime, if you wish to use LDCA circuits without having to wait for the final release, please checkout on the `master` branch, and do the `pip install --user .` from there. It should fix this issue. But please be aware that the code on the `master` branch has only been tested with the next MyQLM version, so you might encounter compatibility issues with the current MyQLM 1.5.1 version.

Let me know if that fixed your issue.

All the best,
Maxime

**Comment by thiblouvet** [comment]
Hi Maxime,thanks for the answer! For now on I've switch to another ansatz, but I might try the master branch and LDCA in the next days.Best regards,Thibaud

    Le vendredi 16 septembre 2022 à 18:14:53 UTC+2, Maxime Oliva ***@***.***> a écrit :  
 
 


Hello Thiblouvet,

Thank you for your input ! Indeed there is a bug with the LDCA circuit in the alpha version of MyQLM-fermion. This bug is fixed in the final release, which will be part of the next MyQLM suite update. This update will be available very soon.

In the meantime, if you wish to use LDCA circuits without having to wait for the final release, please checkout on the master branch, and do the pip install --user . from there. It should fix this issue. But please be aware that the code on the master branch has only been tested with the next MyQLM version, so you might encounter compatibility issues with the current MyQLM 1.5.1 version.

Let me know if that fixed your issue.

All the best,
Maxime

**Comment by moliva7** [comment]
Hello thiblouvet,

Thank you for your answer. Since this is fixed in new incoming release of MyQLM-fermion, I close this issue. Please feel free to open a new one should you encounter bugs in the future.

All the best,
Maxime

**Comment by thiblouvet** [comment]
Hi Maxime,

I've tried to switch to the master branch in order to use ldca, but now I come across the following bug

'''(optimizedmps) tlouvet@gre065091:/nobackup/tlouvet/Documents/VQE/myqlm-fermion$ python example_vqe_hubbard_standard_error.py 
Traceback (most recent call last):
  File "example_vqe_hubbard_standard_error.py", line 296, in <module>
    E_0, E, sigma, overlap, trace = vqe_hubbard(nsites=nsites, u=u, ansatz=ansatz, optimizer=optimizer, nsteps=nsteps, maxiter=maxiter, nbshots=nbshots, exact=exact, visual=visual)
  File "example_vqe_hubbard_standard_error.py", line 59, in vqe_hubbard
    hamiltonian = hamiltonians.make_hubbard_model(t_mat = t_mat, U = u, mu = u/2.)
  File "/nobackup/tlouvet/Documents/VQE/myqlm-fermion/qat/fermion/hamiltonians.py", line 922, in make_hubbard_model
    return ElectronicStructureHamiltonian(hpq=hpq, hpqrs=hpqrs)
  File "/nobackup/tlouvet/Documents/VQE/myqlm-fermion/qat/fermion/hamiltonians.py", line 564, in __init__
    super(ElectronicStructureHamiltonian, self).__init__(self._hpq.shape[0], terms, constant_coeff, do_clean_up=do_clean_up)
  File "/nobackup/tlouvet/Documents/VQE/myqlm-fermion/qat/fermion/hamiltonians.py", line 286, in __init__
    self._preprocess_terms(terms, normal_order)
  File "/nobackup/tlouvet/Documents/VQE/myqlm-fermion/qat/fermion/hamiltonians.py", line 323, in _preprocess_terms
    self.terms = terms if isinstance(terms[0], FermionicTerm) else [FermionicTerm.from_term(term) for term in terms]
  File "/nobackup/tlouvet/Documents/VQE/myqlm-fermion/qat/fermion/hamiltonians.py", line 323, in <listcomp>
    self.terms = terms if isinstance(terms[0], FermionicTerm) else [FermionicTerm.from_term(term) for term in terms]
  File "/nobackup/tlouvet/Documents/VQE/myqlm-fermion/qat/fermion/fermion_algebra.py", line 68, in from_term
    return FermionicTerm(term.coeff, term.op, term.qbits)
  File "/nobackup/tlouvet/Documents/VQE/myqlm-fermion/qat/fermion/fermion_algebra.py", line 33, in __init__
    super(FermionicTerm, self).__init__(coefficient, op, qbits, do_validity_check)
  File "observable.py", line 67, in qat.core.wrappers.observable.Term.__init__
TypeError: __init__() takes exactly 4 positional arguments (5 given)'''

it comes from make_hubbard_model apparently.
Is there a way to go around this?
How do I come back to the alpha version of myqlm?
