### ISSUE TITLE
myqlm can't be installed

### ISSUE THREAD

**Issue by ibouarich** [myQLM/myqlm-fermion#2]
When i use the command " pip install myqlm " I have the following issue : 

Collecting myqlm
  Using cached myqlm-1.5.1-py3-none-any.whl (2.0 kB)
Collecting myqlm-simulators>=1.5.1
  Using cached myqlm_simulators-1.5.4-py3-none-any.whl (19 kB)
Collecting myqlm
  Using cached myqlm-1.5.0-py3-none-any.whl (2.0 kB)
  Using cached myqlm-1.4.1-py3-none-any.whl (2.0 kB)
  Using cached myqlm-1.4.0-py3-none-any.whl (2.0 kB)
  Using cached myqlm-1.2.3-py3-none-any.whl (2.0 kB)
  Using cached myqlm-1.2.2-py3-none-any.whl (2.0 kB)
  Using cached myqlm-1.1.6-py3-none-any.whl (1.8 kB)
  Using cached myqlm-1.1.5-py3-none-any.whl (1.6 kB)
ERROR: Cannot install myqlm==1.1.5, myqlm==1.1.6, myqlm==1.2.2, myqlm==1.2.3, myqlm==1.4.0, myqlm==1.4.1, myqlm==1.5.0 and myqlm==1.5.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    myqlm 1.5.1 depends on qat-lang>=2.1.2
    myqlm 1.5.0 depends on qat-devices>=0.1.3
    myqlm 1.4.1 depends on qat-comm>=1.3.1
    myqlm 1.4.0 depends on qat-comm>=1.3.0
    myqlm 1.2.3 depends on qat-variational>=1.2.3
    myqlm 1.2.2 depends on qat-lang>=2.0.0
    myqlm 1.1.6 depends on qat-comm>=1.1.6
    myqlm 1.1.5 depends on qat-core>=1.2.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by moliva7** [comment]
Hello,

Would you happen to have an older installation of myQLM on your machine ? Can you show me the output you get when typing `pip freeze` in a terminal ?

Best,
Max

**Comment by ibouarich** [comment]
Hello,

I firstly want to thank you for your response. I had installed it a while ago but it didn’t work because I had miniconda. So I tried to uninstall myqlm and install python directly from the website so that I can use myqlm with python not miniconda. However, now when I try to install it again, it doesn’t work.

Here is the output I get when typing pip freeze : 

anaconda-clean @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_be20dd64-61dd-41d9-bf38-a84695fe69507hs6olkf/croots/recipe/anaconda-clean_1652723729651/work
anytree==2.8.0
appnope==0.1.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.8
attrs==22.1.0
backcall==0.2.0
beautifulsoup4==4.11.1
bitstring==3.1.9
bleach==5.0.1
brotlipy==0.7.0
certifi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_05nm_gqf36/croots/recipe/certifi_1663615689491/work/certifi
cffi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_62rp5d8fd4/croots/recipe/cffi_1659598655556/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
conda==22.9.0
conda-content-trust @ file:///tmp/build/80754af9/conda-content-trust_1617045594566/work
conda-package-handling @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_4aholt4czv/croots/recipe/conda-package-handling_1663598478352/work
cryptography @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_b470f7cb-c8f1-42c9-b84f-23789ea77e7c9difcqh4/croots/recipe/cryptography_1652101134392/work
debugpy==1.6.3
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
executing==1.1.0
fastjsonschema==2.16.2
h5py==3.7.0
idna @ file:///tmp/build/80754af9/idna_1637925883363/work
iniconfig==1.1.1
ipykernel==6.16.0
ipython==8.5.0
ipython-genutils==0.2.0
ipywidgets==8.0.2
jedi==0.18.1
Jinja2==3.1.2
jsonschema==4.16.0
jupyter==1.0.0
jupyter-console==6.4.4
jupyter-core==4.11.1
jupyter_client==7.3.5
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.3
lxml==4.9.1
MarkupSafe==2.1.1
matplotlib-inline==0.1.6
mistune==2.0.4
mkl-fft==1.3.1
mkl-random @ file:///opt/concourse/worker/volumes/live/a9eca864-069c-4240-73c8-4e51b036a10d/volume/mkl_random_1639994047876/work
mkl-service==2.4.0
nbclient==0.6.8
nbconvert==7.0.0
nbformat==5.6.1
nest-asyncio==1.5.5
notebook==6.4.12
numpy @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_cer8_sm247/croots/recipe/numpy_and_numpy_base_1659432720132/work
packaging==21.3
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
pluggy==1.0.0
prometheus-client==0.14.1
prompt-toolkit==3.0.31
psutil==5.9.2
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
Pygments==2.13.0
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1635333100036/work
pyparsing==3.0.9
pyrsistent==0.18.1
PySocks @ file:///Users/builder/ci_310/pysocks_1642536366386/work
pytest==7.1.3
python-dateutil==2.8.2
pyzmq==24.0.1
qtconsole==5.3.2
QtPy==2.2.0
requests @ file:///opt/conda/conda-bld/requests_1641824580448/work
ruamel-yaml-conda @ file:///Users/builder/ci_310/ruamel_yaml_1642537156360/work
scipy==1.9.2
Send2Trash==1.8.0
six @ file:///tmp/build/80754af9/six_1623709665295/work
soupsieve==2.3.2.post1
stack-data==0.5.1
terminado==0.15.0
tinycss2==1.1.1
tomli==2.0.1
toolz @ file:///tmp/build/80754af9/toolz_1636545406491/work
tornado==6.2
tqdm @ file:///tmp/build/80754af9/tqdm_1635330843403/work
traitlets==5.4.0
urllib3==1.26.7
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==4.0.3

Best,

Ismail

**Comment by tayral** [comment]
Hi @ibouarich,
can you repost your issue here: https://github.com/myQLM/myqlm-issues/issues? (this is where generic issues on myQLM are handled)
Thanks
