### ISSUE TITLE
callback option not working on scipy optimize minimize plugin

### ISSUE THREAD

**Issue by thiblouvet** [myQLM/myqlm-fermion#3]
I would like to compute intermediate quantities like the overlap at each iteration step in a VQE algorithm. I've tried to use 'callback' in scipy optimize minimize plugin but it doesn't work with COBYLA optimizer.
Thanks in advance!
Thibaud

**Comment by moliva7** [comment]
Hi Thiblouvet,

Could you provide me with a code which shows exactly what you are attempting to do ? 

Best,
Maxime

**Comment by thiblouvet** [comment]
Hi Maxime,here is an example and the output I get showing the "runtime warning"Thanks! All the best,Thibaud

    Le vendredi 21 octobre 2022 à 11:29:56 UTC+2, Maxime Oliva ***@***.***> a écrit :  
 
 


Hi Thilouvet,

Could you provide me with a code which shows exactly what you are attempting to do ?

Best,
Maxime

**Comment by tayral** [comment]
Hello Thibaud,
Here is a workaround for COBYLA (which does not accept callbacks, contrary to e.g Nelder-Mead, CG, Powell...):


```Python
import numpy as np
import scipy
import matplotlib.pyplot as plt
from qat.core import Observable, Term
from qat.fermion import SpinHamiltonian
from qat.lang.AQASM import Program, RY, CNOT
from qat.qpus import get_default_qpu
from qat.plugins import ScipyMinimizePlugin

# we instantiate the Hamiltonian we want to approximate the ground state energy of
def make_random_hamiltonian(nqbits, nterms):
    terms = []
    for _ in range(nterms):
        coeff = np.random.random()
        ops = "".join(np.random.choice(["X", "Z"], size=nqbits))
        qbits = np.random.choice(nqbits, size=nqbits, replace=False)
        terms.append(Term(coefficient=coeff, pauli_op=ops, qbits=qbits))
    hamiltonian = SpinHamiltonian(nqbits, terms=terms)
    return hamiltonian

nqbits = 3
nterms = 5
np.random.seed(1423543) #fixing seed to have reproducible results
hamiltonian = make_random_hamiltonian(nqbits, nterms)

eigvals, eigvec = np.linalg.eigh(hamiltonian.get_matrix(sparse=False))
E0 = min(eigvals)
print("min eigval = ", E0)
psi0 = eigvec[:, np.argmin(eigvals)]

# we construct the variational circuit (ansatz)
prog = Program()
reg = prog.qalloc(hamiltonian.nbqbits)
nparams = 3*nqbits
theta = [prog.new_var(float, '\\theta_%s'%i) for i in range(nparams)]
for it in range(3):
    for qb in range(nqbits):
        RY(theta[nqbits*it + qb])(reg[qb])
    for qb in range(nqbits):
        CNOT(reg[qb], reg[(qb+1)%nqbits])
circ = prog.to_circ()

qpu = get_default_qpu()

energy_list, fid_list = [], []
def my_func(x):
    """returns energy given parameter x, and stores it + the fidelity of state"""
    global energy_list, fid_list
    circ1 = circ.bind_variables({k : v for k, v in zip(circ.get_variables(), x)})
    res0 = qpu.submit(circ1.to_job(observable=hamiltonian)) 
    energy = res0.value
    res = qpu.submit(circ1.to_job())
    psi = np.zeros((2**nqbits,), complex)
    for sample in res:
        psi[sample.state.int] = sample.amplitude
    fid = abs(psi.conj().dot(psi0))**2
    # print(f"E({x}) = {energy}, fid = {fid}")
    energy_list.append(energy)
    fid_list.append(fid)
    return energy

res = scipy.optimize.minimize(my_func, x0=[0]*nparams, method="COBYLA")

plt.plot(energy_list, label= "energies")
plt.plot(fid_list, label="fidelity w.r.t true ground state")
plt.plot([E0]*len(energy_list), label = "true ground state energy")
plt.xlabel("optimization step")
plt.legend()
plt.grid()
```
![image](https://user-images.githubusercontent.com/1186890/197975306-b469be30-c12e-463e-af33-0a5d36cd178e.png)

**Comment by thiblouvet** [comment]
Hi,thanks for the workaround. I've tried to implement it, it works but it gives random results. This must be some initialisation issue but I don't see where it comes from. Files attached

    Le mercredi 26 octobre 2022 à 10:30:33 UTC+2, Thomas Ayral ***@***.***> a écrit :  
 
 


Hello Thibaud,
Here is a workaround for COBYLA (which does not accept callbacks, contrary to e.g Nelder-Mead, CG, Powell...):
import numpy as np
import scipy
import matplotlib.pyplot as plt
from qat.core import Observable, Term
from qat.fermion import SpinHamiltonian
from qat.lang.AQASM import Program, RY, CNOT
from qat.qpus import get_default_qpu
from qat.plugins import ScipyMinimizePlugin

# we instantiate the Hamiltonian we want to approximate the ground state energy of
def make_random_hamiltonian(nqbits, nterms):
    terms = []
    for _ in range(nterms):
        coeff = np.random.random()
        ops = "".join(np.random.choice(["X", "Z"], size=nqbits))
        qbits = np.random.choice(nqbits, size=nqbits, replace=False)
        terms.append(Term(coefficient=coeff, pauli_op=ops, qbits=qbits))
    hamiltonian = SpinHamiltonian(nqbits, terms=terms)
    return hamiltonian

nqbits = 3
nterms = 5
np.random.seed(1423543) #fixing seed to have reproducible results
hamiltonian = make_random_hamiltonian(nqbits, nterms)

eigvals, eigvec = np.linalg.eigh(hamiltonian.get_matrix(sparse=False))
E0 = min(eigvals)
print("min eigval = ", E0)
psi0 = eigvec[:, np.argmin(eigvals)]

# we construct the variational circuit (ansatz)
prog = Program()
reg = prog.qalloc(hamiltonian.nbqbits)
nparams = 3*nqbits
theta = [prog.new_var(float, '\\theta_%s'%i) for i in range(nparams)]
for it in range(3):
    for qb in range(nqbits):
        RY(theta[nqbits*it + qb])(reg[qb])
    for qb in range(nqbits):
        CNOT(reg[qb], reg[(qb+1)%nqbits])
circ = prog.to_circ()

qpu = get_default_qpu()

energy_list, fid_list = [], []
def my_func(x):
    """returns energy given parameter x, and stores it + the fidelity of state"""
    global energy_list, fid_list
    circ1 = circ.bind_variables({k : v for k, v in zip(circ.get_variables(), x)})
    res0 = qpu.submit(circ1.to_job(observable=hamiltonian)) 
    energy = res0.value
    res = qpu.submit(circ1.to_job())
    psi = np.zeros((2**nqbits,), complex)
    for sample in res:
        psi[sample.state.int] = sample.amplitude
    fid = abs(psi.conj().dot(psi0))**2
    # print(f"E({x}) = {energy}, fid = {fid}")
    energy_list.append(energy)
    fid_list.append(fid)
    return energy

res = scipy.optimize.minimize(my_func, x0=[0]*nparams, method="COBYLA")

plt.plot(energy_list, label= "energies")
plt.plot(fid_list, label="fidelity w.r.t true ground state")
plt.plot([E0]*len(energy_list), label = "true ground state energy")
plt.xlabel("optimization step")
plt.legend()
plt.grid()

**Comment by thiblouvet** [comment]
Hi again,
the randomness comes from the circ.get_variables() method, which sometimes gives {'\\theta_{2}': 1.0, '\\theta_{0}': 0.0, '\\theta_{1}': 0.0} and sometimes {'\\theta_{1}': 1.0, '\\theta_{2}': 0.0, '\\theta_{0}': 0.0}
why is the order not corresponding to the label of theta angles?





    Le mercredi 26 octobre 2022 à 12:16:47 UTC+2, Thibaud Louvet ***@***.***> a écrit :  
 
  Hi,thanks for the workaround. I've tried to implement it, it works but it gives random results. This must be some initialisation issue but I don't see where it comes from. Files attached

    Le mercredi 26 octobre 2022 à 10:30:33 UTC+2, Thomas Ayral ***@***.***> a écrit :  
 
 


Hello Thibaud,
Here is a workaround for COBYLA (which does not accept callbacks, contrary to e.g Nelder-Mead, CG, Powell...):
import numpy as np
import scipy
import matplotlib.pyplot as plt
from qat.core import Observable, Term
from qat.fermion import SpinHamiltonian
from qat.lang.AQASM import Program, RY, CNOT
from qat.qpus import get_default_qpu
from qat.plugins import ScipyMinimizePlugin

# we instantiate the Hamiltonian we want to approximate the ground state energy of
def make_random_hamiltonian(nqbits, nterms):
    terms = []
    for _ in range(nterms):
        coeff = np.random.random()
        ops = "".join(np.random.choice(["X", "Z"], size=nqbits))
        qbits = np.random.choice(nqbits, size=nqbits, replace=False)
        terms.append(Term(coefficient=coeff, pauli_op=ops, qbits=qbits))
    hamiltonian = SpinHamiltonian(nqbits, terms=terms)
    return hamiltonian

nqbits = 3
nterms = 5
np.random.seed(1423543) #fixing seed to have reproducible results
hamiltonian = make_random_hamiltonian(nqbits, nterms)

eigvals, eigvec = np.linalg.eigh(hamiltonian.get_matrix(sparse=False))
E0 = min(eigvals)
print("min eigval = ", E0)
psi0 = eigvec[:, np.argmin(eigvals)]

# we construct the variational circuit (ansatz)
prog = Program()
reg = prog.qalloc(hamiltonian.nbqbits)
nparams = 3*nqbits
theta = [prog.new_var(float, '\\theta_%s'%i) for i in range(nparams)]
for it in range(3):
    for qb in range(nqbits):
        RY(theta[nqbits*it + qb])(reg[qb])
    for qb in range(nqbits):
        CNOT(reg[qb], reg[(qb+1)%nqbits])
circ = prog.to_circ()

qpu = get_default_qpu()

energy_list, fid_list = [], []
def my_func(x):
    """returns energy given parameter x, and stores it + the fidelity of state"""
    global energy_list, fid_list
    circ1 = circ.bind_variables({k : v for k, v in zip(circ.get_variables(), x)})
    res0 = qpu.submit(circ1.to_job(observable=hamiltonian)) 
    energy = res0.value
    res = qpu.submit(circ1.to_job())
    psi = np.zeros((2**nqbits,), complex)
    for sample in res:
        psi[sample.state.int] = sample.amplitude
    fid = abs(psi.conj().dot(psi0))**2
    # print(f"E({x}) = {energy}, fid = {fid}")
    energy_list.append(energy)
    fid_list.append(fid)
    return energy

res = scipy.optimize.minimize(my_func, x0=[0]*nparams, method="COBYLA")

plt.plot(energy_list, label= "energies")
plt.plot(fid_list, label="fidelity w.r.t true ground state")
plt.plot([E0]*len(energy_list), label = "true ground state energy")
plt.xlabel("optimization step")
plt.legend()
plt.grid()

**Comment by thiblouvet** [comment]
For instance with this piece of code I randomly get different output from the two 'prints'

    dico={}    print(X)
    print('inside get',{k : v for k, v in zip(circ.get_variables(), X)})
    if isinstance(X, str):
        X = eval(X)
    for i,theta in enumerate(X):
        key = '\\theta_{%s}'%i
        dico[key] = theta
    print(f'dico is {dico}')

    Le mercredi 26 octobre 2022 à 12:45:41 UTC+2, Thibaud Louvet ***@***.***> a écrit :  
 
  Hi again,
the randomness comes from the circ.get_variables() method, which sometimes gives {'\\theta_{2}': 1.0, '\\theta_{0}': 0.0, '\\theta_{1}': 0.0} and sometimes {'\\theta_{1}': 1.0, '\\theta_{2}': 0.0, '\\theta_{0}': 0.0}
why is the order not corresponding to the label of theta angles?





    Le mercredi 26 octobre 2022 à 12:16:47 UTC+2, Thibaud Louvet ***@***.***> a écrit :  
 
  Hi,thanks for the workaround. I've tried to implement it, it works but it gives random results. This must be some initialisation issue but I don't see where it comes from. Files attached

    Le mercredi 26 octobre 2022 à 10:30:33 UTC+2, Thomas Ayral ***@***.***> a écrit :  
 
 


Hello Thibaud,
Here is a workaround for COBYLA (which does not accept callbacks, contrary to e.g Nelder-Mead, CG, Powell...):
import numpy as np
import scipy
import matplotlib.pyplot as plt
from qat.core import Observable, Term
from qat.fermion import SpinHamiltonian
from qat.lang.AQASM import Program, RY, CNOT
from qat.qpus import get_default_qpu
from qat.plugins import ScipyMinimizePlugin

# we instantiate the Hamiltonian we want to approximate the ground state energy of
def make_random_hamiltonian(nqbits, nterms):
    terms = []
    for _ in range(nterms):
        coeff = np.random.random()
        ops = "".join(np.random.choice(["X", "Z"], size=nqbits))
        qbits = np.random.choice(nqbits, size=nqbits, replace=False)
        terms.append(Term(coefficient=coeff, pauli_op=ops, qbits=qbits))
    hamiltonian = SpinHamiltonian(nqbits, terms=terms)
    return hamiltonian

nqbits = 3
nterms = 5
np.random.seed(1423543) #fixing seed to have reproducible results
hamiltonian = make_random_hamiltonian(nqbits, nterms)

eigvals, eigvec = np.linalg.eigh(hamiltonian.get_matrix(sparse=False))
E0 = min(eigvals)
print("min eigval = ", E0)
psi0 = eigvec[:, np.argmin(eigvals)]

# we construct the variational circuit (ansatz)
prog = Program()
reg = prog.qalloc(hamiltonian.nbqbits)
nparams = 3*nqbits
theta = [prog.new_var(float, '\\theta_%s'%i) for i in range(nparams)]
for it in range(3):
    for qb in range(nqbits):
        RY(theta[nqbits*it + qb])(reg[qb])
    for qb in range(nqbits):
        CNOT(reg[qb], reg[(qb+1)%nqbits])
circ = prog.to_circ()

qpu = get_default_qpu()

energy_list, fid_list = [], []
def my_func(x):
    """returns energy given parameter x, and stores it + the fidelity of state"""
    global energy_list, fid_list
    circ1 = circ.bind_variables({k : v for k, v in zip(circ.get_variables(), x)})
    res0 = qpu.submit(circ1.to_job(observable=hamiltonian)) 
    energy = res0.value
    res = qpu.submit(circ1.to_job())
    psi = np.zeros((2**nqbits,), complex)
    for sample in res:
        psi[sample.state.int] = sample.amplitude
    fid = abs(psi.conj().dot(psi0))**2
    # print(f"E({x}) = {energy}, fid = {fid}")
    energy_list.append(energy)
    fid_list.append(fid)
    return energy

res = scipy.optimize.minimize(my_func, x0=[0]*nparams, method="COBYLA")

plt.plot(energy_list, label= "energies")
plt.plot(fid_list, label="fidelity w.r.t true ground state")
plt.plot([E0]*len(energy_list), label = "true ground state energy")
plt.xlabel("optimization step")
plt.legend()
plt.grid()

**Comment by tayral** [comment]
Hello Thibaud,
Thanks for pointing this out. One quick fix is to sort the keys by replacing circ.get_variables() by sorted(circ.get_variables()).

**Comment by thiblouvet** [comment]
Hi Thomas, thanks for the fix, it works!

    Le mercredi 26 octobre 2022 à 13:34:01 UTC+2, Thomas Ayral ***@***.***> a écrit :  
 
 


Hello Thibaud,
Thanks for pointing this out. One quick fix is to sort the keys by replacing circ.get_variables() by sorted(circ.get_variables()).

**Comment by tayral** [comment]
OK, closing the issue. Reopen if needed.
