### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by thiblouvet** [myQLM/myqlm-fermion#5]
Hello,

when installing myqlm on a new laptop I get the following error:

pip install -r requirements.txt 
Collecting anytree
  Using cached anytree-2.8.0-py2.py3-none-any.whl (41 kB)
Collecting bitstring
  Using cached bitstring-3.1.9-py3-none-any.whl (38 kB)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (1.17.4)
Collecting pyscf
  Using cached pyscf-2.1.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.2 MB)
Requirement already satisfied: pytest in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (4.6.9)
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from -r requirements.txt (line 6)) (1.3.3)
Requirement already satisfied: setuptools in /home/tl268768/myqlm/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (44.0.0)
Collecting myqlm
  Using cached myqlm-1.5.1-py3-none-any.whl (2.0 kB)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from anytree->-r requirements.txt (line 1)) (1.14.0)
Collecting h5py>=2.7
  Using cached h5py-3.7.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.5 MB)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/lib/python3/dist-packages (from pytest->-r requirements.txt (line 5)) (4.2.0)
ERROR: Could not find a version that satisfies the requirement qat-lang>=2.1.2 (from myqlm->-r requirements.txt (line 8)) (from versions: 2.0.0, 2.0.1, 2.1.0)
ERROR: No matching distribution found for qat-lang>=2.1.2 (from myqlm->-r requirements.txt (line 8))

There is no previous installation of myqlm on the machine.
Thanks for your help

Thibaud

**Comment by moliva7** [comment]
Hi thiblouvet, 

The new version of MyQLM is out ! Please install/upgrade your myqlm package, and see if let me know if the issue is now resolved.

Best regards,
Maxime

**Comment by thiblouvet** [comment]
The problem is resolved, it came from incompatibility with the python 3.8 installed on the machine actually.
Thanks!

**Comment by moliva7** [comment]
Excellent, glad you worked it out !

Have a nice day,
Maxime
